<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
	<div class="container">
	    <p><h2>You have no access to this page.</h2></p>
	</div>

	<div class="container">
	<!-- generate HTML code<a href="">Sign Up Here!</a> -->
	<?php
	echo $this->tag->linkTo(
		"/login",
		"Login Here"
	);
	?>
	</div>
  </body>
</html>