<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
  	<div class="container" align="right">
	<?php
	echo $this->tag->linkTo(
		"/logout",
		"Logout"
	);
	?>
	</div>
	<div class="container">
	    <p><h2>Profile of <?php echo $user->name ?>:</h2></p>
	</div>
	<div class="container">
		<ul>
		  <li>ID: <?php echo $user->id ?></li>
		  <li>GitHub ID: <?php echo $user->github_id ?></li>
		  <li>Name: <?php echo $user->name ?></li>
		  <li>URL: <?php echo $user->html_url ?></li>
		  <li>Avatar: <img src="<?php echo $user->avatar_url ?>" alt="Avatar" height="42" width="42"></li>
		</ul>
	</div>
  </body>
</html>
